-- Producer: 50, User: 50, Grape: 38, Wine: 99, Pairing: 300, Review: 100 -> 638

INSERT IGNORE INTO Producer (origin, region, region_ex) VALUES ('France', 'Loire Valley', 'Loire Valley 지역은 France의 특별한 기후 조건을 활용하여 다양한 와인 스타일을 선보이고 있습니다.');
INSERT IGNORE INTO Producer (origin, region, region_ex) VALUES ('South Africa', 'Elgin', 'Elgin 지역은 South Africa의 풍부한 역사와 어우러져, 세계적으로 사랑받는 고품질 와인을 생산하는 곳입니다.');
INSERT IGNORE INTO Producer (origin, region, region_ex) VALUES ('Italy', 'Piedmont', 'Piedmont 지역은 Italy의 독창적인 와인 문화를 형성하며, 세계적으로 명성이 높은 와인 생산지입니다.');
INSERT IGNORE INTO Producer (origin, region, region_ex) VALUES ('USA', 'Sonoma', 'Sonoma 지역은 USA의 풍부한 역사와 어우러져, 세계적으로 사랑받는 고품질 와인을 생산하는 곳입니다.');
INSERT IGNORE INTO Producer (origin, region, region_ex) VALUES ('France', 'Bordeaux', 'Bordeaux 지역은 France의 특별한 기후 조건을 활용하여 다양한 와인 스타일을 선보이고 있습니다.');
INSERT IGNORE INTO Producer (origin, region, region_ex) VALUES ('Spain', 'Priorat', 'Priorat 지역은 Spain의 와인 생산 중심지로, 뛰어난 테루아를 자랑하며 독창적인 와인을 만듭니다.');
INSERT IGNORE INTO Producer (origin, region, region_ex) VALUES ('Argentina', 'San Juan', 'San Juan 지역은 Argentina의 자연 환경을 그대로 담아낸 와인으로, 미식가들에게 사랑받는 지역입니다.');
INSERT IGNORE INTO Producer (origin, region, region_ex) VALUES ('Spain', 'Galicia', 'Galicia 지역은 Spain의 독창적인 와인 문화를 형성하며, 세계적으로 명성이 높은 와인 생산지입니다.');
INSERT IGNORE INTO Producer (origin, region, region_ex) VALUES ('Argentina', 'Catamarca', 'Catamarca 지역은 Argentina의 자연 환경을 그대로 담아낸 와인으로, 미식가들에게 사랑받는 지역입니다.');
INSERT IGNORE INTO Producer (origin, region, region_ex) VALUES ('New Zealand', 'Gisborne', 'Gisborne 지역은 New Zealand의 대표적인 와인 산지로, 독특한 포도 품종과 전통적인 와인 양조 방식으로 유명합니다.');
INSERT IGNORE INTO Producer (origin, region, region_ex) VALUES ('Spain', 'Rioja', 'Rioja 지역은 Spain의 와인 생산 중심지로, 뛰어난 테루아를 자랑하며 독창적인 와인을 만듭니다.');
INSERT IGNORE INTO Producer (origin, region, region_ex) VALUES ('South Africa', 'Stellenbosch', 'Stellenbosch 지역은 South Africa의 대표적인 와인 산지로, 독특한 포도 품종과 전통적인 와인 양조 방식으로 유명합니다.');
INSERT IGNORE INTO Producer (origin, region, region_ex) VALUES ('Italy', 'Abruzzo', 'Abruzzo 지역은 Italy의 풍부한 역사와 어우러져, 세계적으로 사랑받는 고품질 와인을 생산하는 곳입니다.');
INSERT IGNORE INTO Producer (origin, region, region_ex) VALUES ('Spain', 'Catalonia', 'Catalonia 지역은 Spain의 와인 생산 중심지로, 뛰어난 테루아를 자랑하며 독창적인 와인을 만듭니다.');
INSERT IGNORE INTO Producer (origin, region, region_ex) VALUES ('USA', 'Finger Lakes', 'Finger Lakes 지역은 USA의 풍부한 역사와 어우러져, 세계적으로 사랑받는 고품질 와인을 생산하는 곳입니다.');
INSERT IGNORE INTO Producer (origin, region, region_ex) VALUES ('Germany', 'Baden', 'Baden 지역은 Germany의 특별한 기후 조건을 활용하여 다양한 와인 스타일을 선보이고 있습니다.');
INSERT IGNORE INTO Producer (origin, region, region_ex) VALUES ('Australia', 'Clare Valley', 'Clare Valley 지역은 Australia의 자연 환경을 그대로 담아낸 와인으로, 미식가들에게 사랑받는 지역입니다.');
INSERT IGNORE INTO Producer (origin, region, region_ex) VALUES ('Argentina', 'Mendoza', 'Mendoza 지역은 Argentina의 와인 생산 중심지로, 뛰어난 테루아를 자랑하며 독창적인 와인을 만듭니다.');
INSERT IGNORE INTO Producer (origin, region, region_ex) VALUES ('Australia', 'Coonawarra', 'Coonawarra 지역은 Australia의 풍부한 역사와 어우러져, 세계적으로 사랑받는 고품질 와인을 생산하는 곳입니다.');
INSERT IGNORE INTO Producer (origin, region, region_ex) VALUES ('Australia', 'Hunter Valley', 'Hunter Valley 지역은 Australia의 대표적인 와인 산지로, 독특한 포도 품종과 전통적인 와인 양조 방식으로 유명합니다.');
INSERT IGNORE INTO Producer (origin, region, region_ex) VALUES ('USA', 'Napa Valley', 'Napa Valley 지역은 USA의 독창적인 와인 문화를 형성하며, 세계적으로 명성이 높은 와인 생산지입니다.');
INSERT IGNORE INTO Producer (origin, region, region_ex) VALUES ('France', 'Alsace', 'Alsace 지역은 France의 자연 환경을 그대로 담아낸 와인으로, 미식가들에게 사랑받는 지역입니다.');
INSERT IGNORE INTO Producer (origin, region, region_ex) VALUES ('USA', 'Columbia Valley', 'Columbia Valley 지역은 USA의 풍부한 역사와 어우러져, 세계적으로 사랑받는 고품질 와인을 생산하는 곳입니다.');
INSERT IGNORE INTO Producer (origin, region, region_ex) VALUES ('Germany', 'Mosel', 'Mosel 지역은 Germany의 대표적인 와인 산지로, 독특한 포도 품종과 전통적인 와인 양조 방식으로 유명합니다.');
INSERT IGNORE INTO Producer (origin, region, region_ex) VALUES ('Germany', 'Nahe', 'Nahe 지역은 Germany의 특별한 기후 조건을 활용하여 다양한 와인 스타일을 선보이고 있습니다.');
INSERT IGNORE INTO Producer (origin, region, region_ex) VALUES ('Italy', 'Umbria', 'Umbria 지역은 Italy의 독창적인 와인 문화를 형성하며, 세계적으로 명성이 높은 와인 생산지입니다.');
INSERT IGNORE INTO Producer (origin, region, region_ex) VALUES ('New Zealand', 'Hawke''s Bay', 'Hawke''s Bay 지역은 New Zealand의 와인 생산 중심지로, 뛰어난 테루아를 자랑하며 독창적인 와인을 만듭니다.');
INSERT IGNORE INTO Producer (origin, region, region_ex) VALUES ('Chile', 'Leyda Valley', 'Leyda Valley 지역은 Chile의 독창적인 와인 문화를 형성하며, 세계적으로 명성이 높은 와인 생산지입니다.');
INSERT IGNORE INTO Producer (origin, region, region_ex) VALUES ('South Africa', 'Franschhoek', 'Franschhoek 지역은 South Africa의 특별한 기후 조건을 활용하여 다양한 와인 스타일을 선보이고 있습니다.');
INSERT IGNORE INTO Producer (origin, region, region_ex) VALUES ('Argentina', 'Salta', 'Salta 지역은 Argentina의 대표적인 와인 산지로, 독특한 포도 품종과 전통적인 와인 양조 방식으로 유명합니다.');
INSERT IGNORE INTO Producer (origin, region, region_ex) VALUES ('Chile', 'Colchagua Valley', 'Colchagua Valley 지역은 Chile의 자연 환경을 그대로 담아낸 와인으로, 미식가들에게 사랑받는 지역입니다.');
INSERT IGNORE INTO Producer (origin, region, region_ex) VALUES ('Italy', 'Tuscany', 'Tuscany 지역은 Italy의 대표적인 와인 산지로, 독특한 포도 품종과 전통적인 와인 양조 방식으로 유명합니다.');
INSERT IGNORE INTO Producer (origin, region, region_ex) VALUES ('New Zealand', 'Central Otago', 'Central Otago 지역은 New Zealand의 자연 환경을 그대로 담아낸 와인으로, 미식가들에게 사랑받는 지역입니다.');
INSERT IGNORE INTO Producer (origin, region, region_ex) VALUES ('New Zealand', 'Marlborough', 'Marlborough 지역은 New Zealand의 대표적인 와인 산지로, 독특한 포도 품종과 전통적인 와인 양조 방식으로 유명합니다.');
INSERT IGNORE INTO Producer (origin, region, region_ex) VALUES ('Germany', 'Franken', 'Franken 지역은 Germany의 와인 생산 중심지로, 뛰어난 테루아를 자랑하며 독창적인 와인을 만듭니다.');
INSERT IGNORE INTO Producer (origin, region, region_ex) VALUES ('South Africa', 'Paarl', 'Paarl 지역은 South Africa의 풍부한 역사와 어우러져, 세계적으로 사랑받는 고품질 와인을 생산하는 곳입니다.');
INSERT IGNORE INTO Producer (origin, region, region_ex) VALUES ('Argentina', 'Patagonia', 'Patagonia 지역은 Argentina의 특별한 기후 조건을 활용하여 다양한 와인 스타일을 선보이고 있습니다.');
INSERT IGNORE INTO Producer (origin, region, region_ex) VALUES ('Germany', 'Pfalz', 'Pfalz 지역은 Germany의 자연 환경을 그대로 담아낸 와인으로, 미식가들에게 사랑받는 지역입니다.');
INSERT IGNORE INTO Producer (origin, region, region_ex) VALUES ('Germany', 'Rheingau', 'Rheingau 지역은 Germany의 독창적인 와인 문화를 형성하며, 세계적으로 명성이 높은 와인 생산지입니다.');
INSERT IGNORE INTO Producer (origin, region, region_ex) VALUES ('New Zealand', 'Martinborough', 'Martinborough 지역은 New Zealand의 풍부한 역사와 어우러져, 세계적으로 사랑받는 고품질 와인을 생산하는 곳입니다.');
INSERT IGNORE INTO Producer (origin, region, region_ex) VALUES ('USA', 'Paso Robles', 'Paso Robles 지역은 USA의 특별한 기후 조건을 활용하여 다양한 와인 스타일을 선보이고 있습니다.');
INSERT IGNORE INTO Producer (origin, region, region_ex) VALUES ('New Zealand', 'Canterbury', 'Canterbury 지역은 New Zealand의 풍부한 역사와 어우러져, 세계적으로 사랑받는 고품질 와인을 생산하는 곳입니다.');
INSERT IGNORE INTO Producer (origin, region, region_ex) VALUES ('Argentina', 'La Rioja', 'La Rioja 지역은 Argentina의 독창적인 와인 문화를 형성하며, 세계적으로 명성이 높은 와인 생산지입니다.');
INSERT IGNORE INTO Producer (origin, region, region_ex) VALUES ('France', 'Provence', 'Provence 지역은 France의 독창적인 와인 문화를 형성하며, 세계적으로 명성이 높은 와인 생산지입니다.');
INSERT IGNORE INTO Producer (origin, region, region_ex) VALUES ('Australia', 'Yarra Valley', 'Yarra Valley 지역은 Australia의 특별한 기후 조건을 활용하여 다양한 와인 스타일을 선보이고 있습니다.');
INSERT IGNORE INTO Producer (origin, region, region_ex) VALUES ('Spain', 'Ribera del Duero', 'Ribera del Duero 지역은 Spain의 풍부한 역사와 어우러져, 세계적으로 사랑받는 고품질 와인을 생산하는 곳입니다.');
INSERT IGNORE INTO Producer (origin, region, region_ex) VALUES ('Spain', 'Navarra', 'Navarra 지역은 Spain의 와인 생산 중심지로, 뛰어난 테루아를 자랑하며 독창적인 와인을 만듭니다.');
INSERT IGNORE INTO Producer (origin, region, region_ex) VALUES ('Chile', 'Aconcagua Valley', 'Aconcagua Valley 지역은 Chile의 풍부한 역사와 어우러져, 세계적으로 사랑받는 고품질 와인을 생산하는 곳입니다.');
INSERT IGNORE INTO Producer (origin, region, region_ex) VALUES ('Australia', 'Barossa Valley', 'Barossa Valley 지역은 Australia의 자연 환경을 그대로 담아낸 와인으로, 미식가들에게 사랑받는 지역입니다.');
INSERT IGNORE INTO Producer (origin, region, region_ex) VALUES ('Chile', 'Maipo Valley', 'Maipo Valley 지역은 Chile의 풍부한 역사와 어우러져, 세계적으로 사랑받는 고품질 와인을 생산하는 곳입니다.');

INSERT IGNORE INTO User (login_id, user_name, password, email, phone_number) VALUES ('ihjfzctg', 'Taylor Johnson', 'yluetdenwjqx', 'qwrww@example.com', '010-1205-4934');
INSERT IGNORE INTO User (login_id, user_name, password, email, phone_number) VALUES ('hxqytaci', 'Chris Anderson', 'piqvqiasnvqo', 'kdrun@example.com', '010-1813-6991');
INSERT IGNORE INTO User (login_id, user_name, password, email, phone_number) VALUES ('qsxtitkv', 'Casey Martin', 'kqebweavrxbb', 'svxzf@hotmail.com', '010-8494-9916');
INSERT IGNORE INTO User (login_id, user_name, password, email, phone_number) VALUES ('tyzmvudq', 'Alex Martin', 'wiidwabrgzcu', 'trbap@yahoo.com', '010-1013-8887');
INSERT IGNORE INTO User (login_id, user_name, password, email, phone_number) VALUES ('tcynbqdw', 'Jamie Johnson', 'ppmejwrnbabh', 'acrpl@example.com', '010-1985-1024');
INSERT IGNORE INTO User (login_id, user_name, password, email, phone_number) VALUES ('fmtbqcwv', 'Chris Johnson', 'pseoqjcabztd', 'scpzl@yahoo.com', '010-2053-8575');
INSERT IGNORE INTO User (login_id, user_name, password, email, phone_number) VALUES ('uesptwqh', 'Jamie Johnson', 'hypcmbwqbfhd', 'cpzbk@example.com', '010-3770-9911');
INSERT IGNORE INTO User (login_id, user_name, password, email, phone_number) VALUES ('jgcourgb', 'Jordan Harris', 'evffkzquxtao', 'ribij@yahoo.com', '010-7993-9748');
INSERT IGNORE INTO User (login_id, user_name, password, email, phone_number) VALUES ('zrlshxao', 'Jamie Harris', 'hzkdqlowfmcw', 'metey@hotmail.com', '010-8708-2637');
INSERT IGNORE INTO User (login_id, user_name, password, email, phone_number) VALUES ('asbqwabb', 'Taylor Johnson', 'fyfoscpvihyj', 'ltfli@gmail.com', '010-2760-2364');
INSERT IGNORE INTO User (login_id, user_name, password, email, phone_number) VALUES ('ilrspjgo', 'John Brown', 'uqvnidaevcnk', 'jyphj@yahoo.com', '010-6165-1429');
INSERT IGNORE INTO User (login_id, user_name, password, email, phone_number) VALUES ('alwxafwz', 'Jordan Anderson', 'hinmckencncf', 'ydrcq@hotmail.com', '010-3527-4815');
INSERT IGNORE INTO User (login_id, user_name, password, email, phone_number) VALUES ('ebcundrp', 'Casey Jackson', 'qyyvyiuuhyti', 'zdkak@yahoo.com', '010-2992-1920');
INSERT IGNORE INTO User (login_id, user_name, password, email, phone_number) VALUES ('xmwdhvtr', 'Jamie Thomas', 'vuhkcqxvgzko', 'vmpkh@yahoo.com', '010-9808-7971');
INSERT IGNORE INTO User (login_id, user_name, password, email, phone_number) VALUES ('jotfxmkp', 'Morgan White', 'sexwfoovhgqx', 'odsvs@hotmail.com', '010-7906-8976');
INSERT IGNORE INTO User (login_id, user_name, password, email, phone_number) VALUES ('nevtvveu', 'Chris Brown', 'bjmmtpafzphw', 'semgz@example.com', '010-1746-4737');
INSERT IGNORE INTO User (login_id, user_name, password, email, phone_number) VALUES ('flabrjek', 'Drew White', 'pmksvdttdjph', 'zylzq@example.com', '010-7392-3102');
INSERT IGNORE INTO User (login_id, user_name, password, email, phone_number) VALUES ('lscfbuje', 'Casey Martin', 'kfhixbbxtfmd', 'czlnq@hotmail.com', '010-7993-6708');
INSERT IGNORE INTO User (login_id, user_name, password, email, phone_number) VALUES ('kqnpmhoc', 'Taylor Taylor', 'htlykejxkxgs', 'tuhho@example.com', '010-4217-5195');
INSERT IGNORE INTO User (login_id, user_name, password, email, phone_number) VALUES ('swstyicj', 'Jordan Smith', 'kysmqsgxwvns', 'xpkmz@yahoo.com', '010-8952-8293');
INSERT IGNORE INTO User (login_id, user_name, password, email, phone_number) VALUES ('hfkhbmsm', 'Taylor Anderson', 'vqrtzdhdyziz', 'gklyp@yahoo.com', '010-6132-1361');
INSERT IGNORE INTO User (login_id, user_name, password, email, phone_number) VALUES ('gqdlcwuw', 'Chris Taylor', 'xmuumbfmfeui', 'fjafu@gmail.com', '010-4329-9082');
INSERT IGNORE INTO User (login_id, user_name, password, email, phone_number) VALUES ('yiycmtfg', 'John Taylor', 'xmzfjivglhdi', 'ubzdr@gmail.com', '010-8835-2363');
INSERT IGNORE INTO User (login_id, user_name, password, email, phone_number) VALUES ('jnifnuia', 'John Smith', 'qnpkxsrsyvoe', 'tujds@hotmail.com', '010-6997-2895');
INSERT IGNORE INTO User (login_id, user_name, password, email, phone_number) VALUES ('oshalxwa', 'Taylor White', 'iljnbudjjjtp', 'iyasb@hotmail.com', '010-3262-1028');
INSERT IGNORE INTO User (login_id, user_name, password, email, phone_number) VALUES ('cscmouue', 'John Smith', 'wwirjzebluse', 'uimfi@gmail.com', '010-4925-8808');
INSERT IGNORE INTO User (login_id, user_name, password, email, phone_number) VALUES ('dcrhghku', 'John Thomas', 'uerxkvcdwiro', 'xpcpm@hotmail.com', '010-3640-3120');
INSERT IGNORE INTO User (login_id, user_name, password, email, phone_number) VALUES ('buvqpzep', 'Casey Martin', 'vjzwoawopgdg', 'uqung@hotmail.com', '010-5931-6648');
INSERT IGNORE INTO User (login_id, user_name, password, email, phone_number) VALUES ('zsosrsqd', 'Casey Jackson', 'gjkkqzdtvfdt', 'bhxxo@hotmail.com', '010-6560-1163');
INSERT IGNORE INTO User (login_id, user_name, password, email, phone_number) VALUES ('clrybqja', 'Morgan Jackson', 'feynyhuxpqdp', 'iewrt@example.com', '010-6440-5799');
INSERT IGNORE INTO User (login_id, user_name, password, email, phone_number) VALUES ('fxznpcwa', 'Drew Anderson', 'twifngwxdgjc', 'vtvot@yahoo.com', '010-7630-6801');
INSERT IGNORE INTO User (login_id, user_name, password, email, phone_number) VALUES ('kssdkztn', 'John White', 'ixyelyrrcbfc', 'obouv@hotmail.com', '010-4917-1160');
INSERT IGNORE INTO User (login_id, user_name, password, email, phone_number) VALUES ('lgdybkxa', 'Jamie Smith', 'brcirlolwtkc', 'wfxeb@hotmail.com', '010-9613-4851');
INSERT IGNORE INTO User (login_id, user_name, password, email, phone_number) VALUES ('xwjmpvlg', 'Jamie Taylor', 'orqdgjdjsptk', 'rjaml@example.com', '010-3476-1607');
INSERT IGNORE INTO User (login_id, user_name, password, email, phone_number) VALUES ('lvhzaehd', 'Drew Harris', 'pfvudnbsddhx', 'qrolf@gmail.com', '010-8306-6375');
INSERT IGNORE INTO User (login_id, user_name, password, email, phone_number) VALUES ('cydauvsf', 'Casey Brown', 'oiralamuqgbt', 'mzjhf@yahoo.com', '010-2115-3354');
INSERT IGNORE INTO User (login_id, user_name, password, email, phone_number) VALUES ('zdiuccil', 'Jordan Harris', 'blwjvsxsqlod', 'gzcqt@gmail.com', '010-3707-2741');
INSERT IGNORE INTO User (login_id, user_name, password, email, phone_number) VALUES ('myuwqzqx', 'Jane Martin', 'cgqunplkvfoe', 'dougv@yahoo.com', '010-1251-8066');
INSERT IGNORE INTO User (login_id, user_name, password, email, phone_number) VALUES ('vugvrttz', 'Jamie Johnson', 'dmcfptqdkhww', 'mkjlc@yahoo.com', '010-5023-8898');
INSERT IGNORE INTO User (login_id, user_name, password, email, phone_number) VALUES ('xjqgivpj', 'Morgan Harris', 'hrrwqrpeuzxb', 'uzvph@gmail.com', '010-3657-3128');
INSERT IGNORE INTO User (login_id, user_name, password, email, phone_number) VALUES ('fbhrvvxp', 'Taylor Martin', 'kjorbyhjhhto', 'rncht@example.com', '010-9955-7434');
INSERT IGNORE INTO User (login_id, user_name, password, email, phone_number) VALUES ('djdextbo', 'Drew Jackson', 'fexpdhthjqpb', 'vbxli@gmail.com', '010-9147-3475');
INSERT IGNORE INTO User (login_id, user_name, password, email, phone_number) VALUES ('zmrhtdhn', 'Alex Taylor', 'odkyzhmwbdfk', 'mbjnu@gmail.com', '010-3070-3866');
INSERT IGNORE INTO User (login_id, user_name, password, email, phone_number) VALUES ('znauuvzx', 'Alex Thomas', 'pcfmouqbdsvg', 'xsjci@hotmail.com', '010-3059-4964');
INSERT IGNORE INTO User (login_id, user_name, password, email, phone_number) VALUES ('blzwozsm', 'John Jackson', 'famccywybemi', 'catlw@gmail.com', '010-3196-9459');
INSERT IGNORE INTO User (login_id, user_name, password, email, phone_number) VALUES ('iznbnlmp', 'Jamie White', 'aoxoqdkiyqkf', 'lzbui@hotmail.com', '010-1667-7953');
INSERT IGNORE INTO User (login_id, user_name, password, email, phone_number) VALUES ('mmdrqnkx', 'Chris Harris', 'euhatqjquspm', 'aetlh@hotmail.com', '010-7072-3773');
INSERT IGNORE INTO User (login_id, user_name, password, email, phone_number) VALUES ('umbwinpc', 'Jordan Johnson', 'dnuvqvseftsk', 'dtjlz@example.com', '010-6813-7805');
INSERT IGNORE INTO User (login_id, user_name, password, email, phone_number) VALUES ('qastiwle', 'Jane Taylor', 'zladihgjbtyt', 'ghuup@example.com', '010-6060-8053');
INSERT IGNORE INTO User (login_id, user_name, password, email, phone_number) VALUES ('grlkbkol', 'John Anderson', 'mtrjvcjffjto', 'naepw@gmail.com', '010-8620-5257');

INSERT IGNORE INTO Grape (grape_name, grape_ex) VALUES ('Merlot', '메를로는 부드럽고 둥근 질감으로 유명하며, 블랙베리와 초콜릿 노트를 가진 레드 와인을 만듭니다.');
INSERT IGNORE INTO Grape (grape_name, grape_ex) VALUES ('Roussanne', '루산느는 허브와 꿀 향이 특징인 화이트 와인 품종으로, 주로 프랑스 남부에서 생산됩니다.');
INSERT IGNORE INTO Grape (grape_name, grape_ex) VALUES ('Fiano', '피아노는 꿀과 열대 과일 향을 가진 이탈리아 화이트 와인 품종입니다.');
INSERT IGNORE INTO Grape (grape_name, grape_ex) VALUES ('Tempranillo', '템프라니요는 스페인의 대표적인 레드 와인 품종으로, 체리와 담배 향이 조화를 이룹니다.');
INSERT IGNORE INTO Grape (grape_name, grape_ex) VALUES ('Touriga Nacional', '투리가 내셔널은 포르투갈의 대표 품종으로, 강렬한 향과 타닌이 특징입니다.');
INSERT IGNORE INTO Grape (grape_name, grape_ex) VALUES ('Grüner Veltliner', '그뤼너 벨트리너는 오스트리아의 대표 품종으로, 신선한 허브와 감귤 풍미가 특징입니다.');
INSERT IGNORE INTO Grape (grape_name, grape_ex) VALUES ('Cabernet Franc', '카베르네 프랑은 블렌드와 단독 와인에 모두 사용되며, 허브와 붉은 과일 풍미가 특징입니다.');
INSERT IGNORE INTO Grape (grape_name, grape_ex) VALUES ('Sémillon', '세미용은 꿀과 건과일 향이 특징이며, 달콤한 와인과 드라이 와인에 모두 사용됩니다.');
INSERT IGNORE INTO Grape (grape_name, grape_ex) VALUES ('Sangiovese', '산지오베제는 이탈리아의 대표 품종으로, 체리와 허브 풍미가 돋보이는 레드 와인을 만듭니다.');
INSERT IGNORE INTO Grape (grape_name, grape_ex) VALUES ('Barbera', '바르베라는 높은 산미와 밝은 체리 향으로 유명한 이탈리아 레드 와인 품종입니다.');
INSERT IGNORE INTO Grape (grape_name, grape_ex) VALUES ('Lambrusco', '람브루스코는 붉은 과일 풍미와 스파클링 스타일로 유명한 이탈리아 와인 품종입니다.');
INSERT IGNORE INTO Grape (grape_name, grape_ex) VALUES ('Pinot Grigio', '피노 그리지오는 가벼운 화이트 와인으로, 배와 사과 풍미가 특징입니다.');
INSERT IGNORE INTO Grape (grape_name, grape_ex) VALUES ('Chardonnay', '샤르도네는 다양한 스타일의 화이트 와인으로 생산되며, 사과와 바닐라 향을 가진 것으로 유명합니다.');
INSERT IGNORE INTO Grape (grape_name, grape_ex) VALUES ('Pedro Ximénez', '페드로 히메네스는 매우 달콤한 스페인 와인 품종으로, 디저트 와인에 주로 사용됩니다.');
INSERT IGNORE INTO Grape (grape_name, grape_ex) VALUES ('Verdelho', '베르델로는 상쾌한 산미와 열대 과일 향이 돋보이는 화이트 와인 품종입니다.');
INSERT IGNORE INTO Grape (grape_name, grape_ex) VALUES ('Syrah', '시라(또는 쉬라즈)는 강렬한 블랙 페퍼와 다크 초콜릿 향을 가진 풀바디 레드 와인으로 유명합니다.');
INSERT IGNORE INTO Grape (grape_name, grape_ex) VALUES ('Cabernet Sauvignon', '카베르네 소비뇽은 풀바디 레드 와인으로 잘 알려져 있으며, 블랙커런트와 스파이스의 풍미가 특징입니다.');
INSERT IGNORE INTO Grape (grape_name, grape_ex) VALUES ('Grenache', '그르나슈는 붉은 과일과 허브 향이 특징이며, 종종 블렌드 와인의 주요 품종으로 사용됩니다.');
INSERT IGNORE INTO Grape (grape_name, grape_ex) VALUES ('Tannat', '타나는 강렬한 타닌과 다크 초콜릿 풍미가 돋보이는 레드 와인 품종입니다.');
INSERT IGNORE INTO Grape (grape_name, grape_ex) VALUES ('Torrontés', '토론테스는 아르헨티나의 독특한 화이트 와인 품종으로, 꽃 향과 열대 과일 풍미가 돋보입니다.');
INSERT IGNORE INTO Grape (grape_name, grape_ex) VALUES ('Petit Verdot', '프티 베르도는 블랙커런트와 제비꽃 향이 돋보이며, 종종 블렌드에 사용되는 레드 와인 품종입니다.');
INSERT IGNORE INTO Grape (grape_name, grape_ex) VALUES ('Nebbiolo', '네비올로는 타닌이 강하고 체리와 장미 향이 특징인 이탈리아 레드 와인 품종입니다.');
INSERT IGNORE INTO Grape (grape_name, grape_ex) VALUES ('Moscato', '모스카토는 달콤한 맛과 꽃 향이 특징이며, 종종 디저트 와인으로 사용됩니다.');
INSERT IGNORE INTO Grape (grape_name, grape_ex) VALUES ('Riesling', '리슬링은 높은 산미와 복합적인 향으로 유명하며, 특히 달콤한 화이트 와인으로 많이 생산됩니다.');
INSERT IGNORE INTO Grape (grape_name, grape_ex) VALUES ('Mourvèdre', '무르베드르는 스파이시하고 다크한 풍미를 가진 레드 와인 품종입니다.');
INSERT IGNORE INTO Grape (grape_name, grape_ex) VALUES ('Trebbiano', '트레비아노는 신선한 산미와 부드러운 풍미를 가진 이탈리아 화이트 와인 품종입니다.');
INSERT IGNORE INTO Grape (grape_name, grape_ex) VALUES ('Cinsault', '생소는 밝은 과일 향과 부드러운 질감이 특징인 레드 와인 품종입니다.');
INSERT IGNORE INTO Grape (grape_name, grape_ex) VALUES ('Pinot Noir', '피노 누아는 섬세하고 복합적인 향으로 사랑받으며, 체리와 라즈베리 풍미가 돋보이는 레드 와인 품종입니다.');
INSERT IGNORE INTO Grape (grape_name, grape_ex) VALUES ('Corvina', '코르비나는 이탈리아 발폴리첼라 와인의 주요 품종으로, 체리와 아몬드 향이 특징입니다.');
INSERT IGNORE INTO Grape (grape_name, grape_ex) VALUES ('Sauvignon Blanc', '소비뇽 블랑은 신선한 허브와 감귤 향이 돋보이는 화이트 와인 품종입니다.');
INSERT IGNORE INTO Grape (grape_name, grape_ex) VALUES ('Malbec', '말벡은 풍부한 블랙베리와 자두 향이 돋보이는 풀바디 레드 와인으로 잘 알려져 있습니다.');
INSERT IGNORE INTO Grape (grape_name, grape_ex) VALUES ('Aglianico', '알리아니코는 이탈리아의 남부에서 주로 생산되며, 다크 체리와 초콜릿 풍미가 돋보입니다.');
INSERT IGNORE INTO Grape (grape_name, grape_ex) VALUES ('Gamay', '가메는 밝고 신선한 레드 와인으로, 라즈베리와 체리 향을 가지고 있습니다.');
INSERT IGNORE INTO Grape (grape_name, grape_ex) VALUES ('Gewürztraminer', '게뷔르츠트라미너는 독특한 향신료와 장미 향이 특징인 화이트 와인 품종입니다.');
INSERT IGNORE INTO Grape (grape_name, grape_ex) VALUES ('Aligoté', '알리고테는 상쾌한 산미와 레몬 향이 특징인 화이트 와인 품종입니다.');
INSERT IGNORE INTO Grape (grape_name, grape_ex) VALUES ('Carmenère', '까르메네르는 칠레의 대표 품종으로, 블랙커런트와 초콜릿 향이 조화를 이룹니다.');
INSERT IGNORE INTO Grape (grape_name, grape_ex) VALUES ('Viognier', '비오니에는 복숭아와 아카시아 꽃 향을 가진 화이트 와인 품종입니다.');
INSERT IGNORE INTO Grape (grape_name, grape_ex) VALUES ('Arneis', '아르네이스는 신선한 배와 꽃 향을 가진 이탈리아 화이트 와인 품종입니다.');

INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('돔 페리뇽', 'Dom Perignon', 'Low', 'Low', 'Light', 'High', 'White', 'Herbal', 111000, 34, 5, 2024, 18);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('샤투 말구스', 'Chateau Margaux', 'Medium', 'Medium', 'Medium', 'Low', 'Red', 'Nutty', 230000, 16, 10, 2019, 23);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('카바넷 싸빅논 에스테이트', 'Cabernet Sauvignon Estate', 'High', 'High', 'Light', 'Medium', 'Sparkling', 'Woody', 105000, 36, 32, 2013, 37);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('스크리밍 이글', 'Screaming Eagle', 'Low', 'Medium', 'Full', 'Medium', 'Sparkling', 'Woody', 347000, 22, 6, 2015, 26);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('오셔닉 레드', 'Oceanic Red', 'Medium', 'Low', 'Full', 'Low', 'Red', 'Woody', 390000, 1, 50, 2018, 15);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('아우로라 릿지', 'Aurora Ridge', 'High', 'High', 'Light', 'Low', 'White', 'Spicy', 484000, 31, 5, 1997, 17);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('서밋 실렉트', 'Summit Select', 'Low', 'High', 'Medium', 'High', 'White', 'Spicy', 58000, 22, 21, 2017, 46);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('이클립스 느와르', 'Eclipse Noir', 'High', 'High', 'Full', 'Low', 'Red', 'Floral', 60000, 20, 15, 2021, 48);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('선셋 하비스트', 'Sunset Harvest', 'Low', 'Low', 'Full', 'Low', 'White', 'Floral', 372000, 37, 28, 2009, 25);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('에코 헤리티지', 'Echo Heritage', 'Medium', 'Low', 'Light', 'High', 'Red', 'Floral', 475000, 31, 18, 1997, 16);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('도메인 레로이 무시그니', 'Domaine Leroy Musigny', 'Medium', 'Low', 'Full', 'Medium', 'Red', 'Woody', 204000, 18, 26, 2023, 31);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('샤르도네 리저브', 'Chardonnay Reserve', 'Low', 'Low', 'Light', 'Low', 'Red', 'Nutty', 213000, 29, 10, 2001, 47);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('무톤 로쓰차일드', 'Mouton Rothschild', 'High', 'Medium', 'Light', 'Low', 'White', 'Fruity', 471000, 35, 28, 2003, 10);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('캐스캐이드 샤르도네', 'Cascade Chardonnay', 'High', 'High', 'Light', 'Low', 'White', 'Nutty', 253000, 30, 36, 2020, 47);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('에메랄드 이스테이트', 'Emerald Estate', 'High', 'Medium', 'Full', 'High', 'White', 'Herbal', 331000, 12, 6, 2009, 13);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('루미너스 샤로도네', 'Luminous Chardonnay', 'Medium', 'Medium', 'Medium', 'Medium', 'Sparkling', 'Herbal', 282000, 11, 41, 2015, 46);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('브리즈 블랑크', 'Breeze Blanc', 'Medium', 'Low', 'Full', 'High', 'White', 'Herbal', 415000, 37, 26, 2013, 16);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('미드나이트 블러섬', 'Midnight Blossom', 'High', 'Medium', 'Medium', 'Low', 'White', 'Herbal', 230000, 12, 25, 2002, 15);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('피놋 느와르 클래식', 'Pinot Noir Classic', 'Low', 'High', 'Medium', 'Medium', 'White', 'Fruity', 113000, 38, 4, 2007, 24);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('트와일라잇 밸리', 'Twilight Valley', 'High', 'High', 'Full', 'Medium', 'Red', 'Nutty', 470000, 19, 45, 2009, 10);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('스칼렛 셀러', 'Scarlet Cellar', 'High', 'High', 'Light', 'Low', 'Sparkling', 'Herbal', 396000, 16, 21, 2012, 10);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('실버 오크', 'Silver Oak', 'Medium', 'Low', 'Light', 'Low', 'Sparkling', 'Fruity', 235000, 27, 47, 2012, 25);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('아메씨트 헤리티지', 'Amethyst Heritage', 'Medium', 'Medium', 'Light', 'High', 'Sparkling', 'Woody', 368000, 5, 30, 2000, 42);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('사씨카야', 'Sassicaia', 'Low', 'High', 'Light', 'Low', 'White', 'Nutty', 242000, 32, 19, 2020, 44);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('벨벳 크리퀏', 'Veuve Clicquot', 'High', 'Medium', 'Light', 'Medium', 'White', 'Fruity', 418000, 26, 3, 2018, 44);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('하모니 말백', 'Harmony Malbec', 'Medium', 'Low', 'Medium', 'High', 'Red', 'Fruity', 51000, 9, 13, 2001, 28);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('세레니티 로즈', 'Serenity Rose', 'High', 'High', 'Medium', 'High', 'Red', 'Woody', 202000, 5, 28, 2013, 49);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('스텔라 사우비곤', 'Stellar Sauvignon', 'Medium', 'Low', 'Light', 'High', 'Sparkling', 'Herbal', 107000, 13, 20, 2020, 43);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('펄 빈티지', 'Pearl Vintage', 'Low', 'Low', 'Medium', 'Low', 'Sparkling', 'Floral', 322000, 29, 29, 1999, 32);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('문스톤 리저브', 'Moonstone Reserve', 'High', 'Low', 'Light', 'High', 'White', 'Spicy', 309000, 34, 48, 2011, 38);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('로매인-콘티', 'Romanee-Conti', 'High', 'Medium', 'Medium', 'Low', 'Red', 'Fruity', 185000, 18, 43, 2015, 46);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('호라이즌 스파클링', 'Horizon Sparkling', 'Low', 'Low', 'Medium', 'Low', 'Sparkling', 'Nutty', 184000, 30, 42, 2001, 25);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('골든 바인야드', 'Golden Vineyard', 'Low', 'Low', 'Medium', 'Low', 'Sparkling', 'Nutty', 104000, 4, 1, 2003, 15);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('안티노리 티그나넬로', 'Antinori Tignanello', 'Medium', 'Medium', 'Full', 'Medium', 'Sparkling', 'Floral', 80000, 2, 50, 2020, 31);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('샤투 라퉈', 'Chateau Latour', 'Medium', 'Low', 'Light', 'Low', 'White', 'Nutty', 471000, 35, 28, 2023, 45);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('진판델 헤리티지', 'Zinfandel Heritage', 'Medium', 'High', 'Full', 'High', 'Red', 'Fruity', 381000, 12, 15, 2007, 30);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('마제스틱 리저브', 'Majestic Reserve', 'Medium', 'Low', 'Medium', 'Low', 'White', 'Nutty', 281000, 11, 8, 2001, 16);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('오퍼스 원', 'Opus One', 'Medium', 'High', 'Full', 'Medium', 'Red', 'Woody', 332000, 30, 18, 2019, 13);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('페트러스', 'Petrus', 'High', 'Low', 'Medium', 'Low', 'Red', 'Nutty', 436000, 38, 31, 2005, 21);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('루비 리저브', 'Ruby Reserve', 'Medium', 'High', 'Full', 'High', 'White', 'Floral', 139000, 19, 39, 2003, 50);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('라디언트 멀롯', 'Radiant Merlot', 'High', 'Low', 'Light', 'Medium', 'Sparkling', 'Floral', 468000, 27, 41, 2011, 45);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('말벡 시그니쳐', 'Malbec Signature', 'Medium', 'Low', 'Light', 'High', 'Red', 'Nutty', 51000, 33, 38, 2017, 48);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('셀레스티얼 칼버넷', 'Celestial Cabernet', 'Medium', 'Low', 'Medium', 'Medium', 'Sparkling', 'Spicy', 370000, 11, 1, 2019, 20);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('클라우디 베이', 'Cloudy Bay', 'Medium', 'Low', 'Full', 'Low', 'White', 'Nutty', 276000, 26, 32, 2002, 42);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('심포니 블랜드', 'Symphony Blend', 'Low', 'Medium', 'Medium', 'High', 'Red', 'Herbal', 311000, 11, 38, 1995, 19);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('펜폴즈 그랑게', 'Penfolds Grange', 'High', 'Low', 'Light', 'Medium', 'White', 'Spicy', 167000, 34, 9, 2013, 10);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('크리스탈 바렐', 'Crystal Barrel', 'Low', 'Low', 'Light', 'High', 'White', 'Herbal', 372000, 28, 11, 2011, 17);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('엠버 진판델', 'Amber Zinfandel', 'Medium', 'Medium', 'Medium', 'Low', 'Red', 'Herbal', 202000, 29, 36, 1998, 37);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('벨벳 피놋', 'Velvet Pinot', 'Low', 'Low', 'Light', 'Medium', 'White', 'Woody', 315000, 6, 9, 2006, 19);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('스카이 헤븐', 'Sky Haven', 'Medium', 'Medium', 'Full', 'Low', 'Sparkling', 'Nutty', 423000, 3, 29, 2019, 35);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('섀도우 위스퍼 파라다이스', 'Shadow Whisper Paradise', 'Medium', 'Medium', 'Light', 'Low', 'Red', 'Woody', 62000, 2, 15, 2011, 18);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('리버 비전 문', 'River Vision Moon', 'High', 'High', 'Full', 'High', 'White', 'Spicy', 120000, 29, 2, 1998, 15);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('가든 위스퍼', 'Garden Whisper', 'Low', 'Low', 'Full', 'Medium', 'Red', 'Spicy', 178000, 4, 38, 2019, 21);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('브리즈 섀도우 문', 'Breeze Shadow Moon', 'Low', 'Medium', 'Full', 'High', 'Sparkling', 'Floral', 221000, 8, 43, 2010, 43);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('위스퍼 헤이븐', 'Whisper Haven', 'Medium', 'High', 'Medium', 'Medium', 'Sparkling', 'Woody', 147000, 38, 27, 2014, 46);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('메도우 선', 'Meadow Sun', 'Medium', 'Low', 'Medium', 'Low', 'Sparkling', 'Herbal', 193000, 17, 3, 2010, 23);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('글로리 파라다이스', 'Glory Paradise', 'Medium', 'High', 'Full', 'High', 'White', 'Spicy', 60000, 27, 20, 2012, 12);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('스카이 미스터리 파라다이스', 'Sky Mystery Paradise', 'Medium', 'Low', 'Medium', 'Medium', 'Red', 'Nutty', 67000, 21, 15, 1995, 20);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('위스퍼 미스터리 글로리', 'Whisper Mystery Glory', 'Medium', 'High', 'Light', 'Low', 'Sparkling', 'Herbal', 173000, 26, 33, 2016, 49);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('리버 밸리 스타', 'River Valley Star', 'High', 'High', 'Light', 'Low', 'White', 'Spicy', 384000, 28, 28, 2005, 18);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('드림 파라다이스', 'Dream Paradise', 'Medium', 'Medium', 'Full', 'Low', 'Red', 'Floral', 224000, 17, 45, 1999, 32);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('파라다이스 하모니', 'Paradise Harmony', 'Medium', 'Low', 'Full', 'Medium', 'White', 'Herbal', 309000, 38, 13, 2008, 25);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('밸리 헤이븐 메도우', 'Valley Haven Meadow', 'Low', 'High', 'Light', 'High', 'White', 'Fruity', 429000, 21, 23, 1999, 46);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('섀도우 비전', 'Shadow Vision', 'High', 'High', 'Medium', 'Medium', 'White', 'Woody', 295000, 25, 19, 2009, 35);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('드림 미스터리', 'Dream Mystery', 'Medium', 'Low', 'Full', 'High', 'Sparkling', 'Herbal', 100000, 25, 23, 2022, 16);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('마운틴 비전', 'Mountain Vision', 'High', 'Medium', 'Medium', 'Low', 'Sparkling', 'Woody', 238000, 15, 41, 1996, 12);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('블러섬 마운틴 문', 'Blossom Mountain Moon', 'Medium', 'Low', 'Full', 'Medium', 'Sparkling', 'Nutty', 60000, 26, 21, 2002, 32);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('미라클 섀도우', 'Miracle Shadow', 'Low', 'High', 'Full', 'High', 'Sparkling', 'Spicy', 147000, 27, 29, 1999, 42);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('브리즈 리버 에코', 'Breeze River Echo', 'Medium', 'Medium', 'Medium', 'Low', 'Sparkling', 'Spicy', 123000, 12, 23, 1995, 15);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('드림 선', 'Dream Sun', 'Low', 'Low', 'Full', 'Low', 'White', 'Nutty', 460000, 9, 23, 2019, 15);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('하모니 스카이 미스터리', 'Harmony Sky Mystery', 'High', 'High', 'Medium', 'Medium', 'Sparkling', 'Floral', 463000, 1, 10, 2018, 27);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('리버 가든', 'River Garden', 'Low', 'High', 'Medium', 'Low', 'White', 'Nutty', 249000, 35, 35, 2024, 42);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('문 마운틴 섀도우', 'Moon Mountain Shadow', 'Low', 'High', 'Full', 'Medium', 'Red', 'Herbal', 200000, 8, 30, 2019, 26);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('리버 포레스트', 'River Forest', 'Medium', 'Medium', 'Light', 'Low', 'White', 'Spicy', 69000, 11, 4, 2022, 48);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('메도우 브리즈 비전', 'Meadow Breeze Vision', 'Medium', 'Low', 'Full', 'High', 'Sparkling', 'Fruity', 152000, 17, 43, 2015, 39);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('문 선 미라클', 'Moon Sun Miracle', 'Low', 'Medium', 'Full', 'Medium', 'Red', 'Spicy', 267000, 18, 42, 2004, 47);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('블러섬 스카이 섀도우', 'Blossom Sky Shadow', 'High', 'Medium', 'Light', 'Medium', 'Red', 'Fruity', 322000, 30, 1, 2013, 40);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('하모니 스카이 드림', 'Harmony Sky Dream', 'High', 'High', 'Light', 'Medium', 'White', 'Herbal', 170000, 21, 19, 2023, 29);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('선 리버 미스터리', 'Sun River Mystery', 'High', 'High', 'Full', 'Low', 'White', 'Nutty', 134000, 22, 35, 2023, 35);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('미스터리 마운틴 선', 'Mystery Mountain Sun', 'Medium', 'High', 'Light', 'High', 'Red', 'Nutty', 458000, 6, 38, 2000, 20);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('글로리 스타', 'Glory Star', 'High', 'High', 'Light', 'Low', 'White', 'Spicy', 304000, 3, 24, 2018, 31);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('밸리 스카이', 'Valley Sky', 'Low', 'Medium', 'Light', 'Medium', 'Red', 'Floral', 353000, 18, 12, 1998, 34);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('글로리 리버 포레스트', 'Glory River Forest', 'Low', 'High', 'Medium', 'High', 'White', 'Fruity', 368000, 18, 19, 2004, 24);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('하모니 포레스트', 'Harmony Forest', 'High', 'High', 'Full', 'Low', 'Sparkling', 'Spicy', 325000, 28, 39, 1995, 40);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('하모니 메도우', 'Harmony Meadow', 'Low', 'Medium', 'Light', 'High', 'White', 'Woody', 340000, 7, 11, 2008, 36);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('메도우 문 미라클', 'Meadow Moon Miracle', 'High', 'Low', 'Medium', 'Low', 'White', 'Herbal', 395000, 2, 42, 2023, 34);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('비전 위스퍼', 'Vision Whisper', 'Medium', 'Low', 'Medium', 'Low', 'Sparkling', 'Spicy', 451000, 9, 35, 2002, 27);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('위스퍼 라이트하우스', 'Whisper Lighthouse', 'Low', 'Low', 'Light', 'Medium', 'Red', 'Woody', 149000, 32, 5, 2021, 39);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('메도우 하모니', 'Meadow Harmony', 'Medium', 'High', 'Full', 'Low', 'Sparkling', 'Spicy', 202000, 20, 45, 2006, 33);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('스카이 파라다이스 포레스트', 'Sky Paradise Forest', 'Low', 'Medium', 'Light', 'Low', 'Red', 'Woody', 318000, 30, 21, 1996, 37);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('미스터리 미라클 위스퍼', 'Mystery Miracle Whisper', 'High', 'Medium', 'Medium', 'Medium', 'Sparkling', 'Floral', 364000, 31, 23, 2008, 31);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('메도우 선 마운틴', 'Meadow Sun Mountain', 'Medium', 'High', 'Full', 'High', 'White', 'Woody', 209000, 18, 5, 2011, 24);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('비전 문', 'Vision Moon', 'Low', 'High', 'Full', 'High', 'White', 'Woody', 212000, 18, 13, 1998, 45);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('파라다이스 스카이 미스터리', 'Paradise Sky Mystery', 'Low', 'High', 'Medium', 'High', 'White', 'Floral', 406000, 18, 38, 1998, 23);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('브리즈 비전 메도우', 'Breeze Vision Meadow', 'High', 'Low', 'Full', 'Medium', 'Sparkling', 'Floral', 116000, 2, 32, 2015, 24);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('블러섬 에코', 'Blossom Echo', 'Medium', 'Medium', 'Medium', 'High', 'Sparkling', 'Spicy', 427000, 35, 20, 2022, 37);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('미라클 섀도우 하모니', 'Miracle Shadow Harmony', 'Medium', 'Low', 'Light', 'Medium', 'Red', 'Woody', 413000, 38, 15, 2010, 11);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('라이트하우스 선', 'Lighthouse Sun', 'High', 'Low', 'Medium', 'Low', 'White', 'Spicy', 290000, 27, 29, 2004, 45);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('헤이븐 브리즈 글로리', 'Haven Breeze Glory', 'Medium', 'Low', 'Light', 'Low', 'White', 'Fruity', 87000, 12, 7, 1997, 24);
INSERT IGNORE INTO Wine (kor_name, eng_name, acidity, sweetness, body, tanin, type, aroma, price, grape_id, producer_id, vintage, alcohol_content) VALUES ('빈티지 블리스', 'Vintage Blliss', 'Medium', 'Low', 'Light', 'Low', 'White', 'Fruity', 88000, 12, 7, 1997, 24);

INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('1', '잡채');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('1', '초콜릿');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('1', '연어');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('2', '잡채');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('2', '토마토 요리');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('2', '햄버거');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('3', '해물파전');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('3', '해산물');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('3', '브루스케타');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('4', '족발');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('4', '양갈비');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('4', '소고기 타르타르');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('5', '해물파전');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('5', '피자');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('5', '굴');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('6', '잡채');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('6', '초콜릿');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('6', '훈제오리');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('7', '불고기');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('7', '바베큐');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('7', '브루스케타');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('8', '해물파전');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('8', '굴');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('8', '치즈');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('9', '불고기');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('9', '해산물');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('9', '과일');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('10', '불고기');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('10', '양갈비');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('10', '과일');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('11', '해물파전');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('11', '치즈');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('11', '굴');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('12', '불고기');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('12', '피자');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('12', '샐러드');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('13', '불고기');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('13', '굴');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('13', '치킨');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('14', '족발');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('14', '치즈');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('14', '훈제오리');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('15', '갈비찜');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('15', '파스타');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('15', '브루스케타');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('16', '잡채');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('16', '초콜릿');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('16', '피자');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('17', '잡채');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('17', '훈제오리');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('17', '토마토 요리');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('18', '잡채');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('18', '피자');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('18', '햄버거');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('19', '갈비찜');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('19', '토마토 요리');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('19', '양갈비');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('20', '불고기');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('20', '샐러드');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('20', '훈제오리');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('21', '잡채');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('21', '양갈비');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('21', '피자');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('22', '갈비찜');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('22', '피자');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('22', '토마토 요리');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('23', '잡채');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('23', '연어');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('23', '치즈');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('24', '해물파전');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('24', '치즈');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('24', '브루스케타');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('25', '불고기');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('25', '과일');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('25', '브루스케타');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('26', '갈비찜');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('26', '초콜릿');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('26', '샐러드');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('27', '족발');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('27', '브루스케타');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('27', '해산물');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('28', '불고기');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('28', '버섯 요리');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('28', '해산물');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('29', '족발');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('29', '스테이크');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('29', '해산물');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('30', '불고기');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('30', '치킨');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('30', '연어');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('31', '족발');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('31', '버섯 요리');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('31', '브루스케타');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('32', '해물파전');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('32', '초콜릿');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('32', '스테이크');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('33', '해물파전');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('33', '버섯 요리');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('33', '양갈비');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('34', '족발');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('34', '연어');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('34', '해산물');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('35', '회');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('35', '바베큐');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('35', '파스타');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('36', '불고기');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('36', '굴');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('36', '양갈비');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('37', '불고기');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('37', '연어');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('37', '치즈');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('38', '잡채');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('38', '연어');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('38', '초콜릿');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('39', '불고기');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('39', '소고기 타르타르');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('39', '버섯 요리');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('40', '해물파전');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('40', '양갈비');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('40', '해산물');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('41', '족발');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('41', '감자튀김');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('41', '치킨');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('42', '잡채');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('42', '피자');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('42', '파스타');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('43', '불고기');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('43', '버섯 요리');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('43', '훈제오리');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('44', '회');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('44', '햄버거');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('44', '피자');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('45', '갈비찜');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('45', '연어');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('45', '과일');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('46', '불고기');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('46', '햄버거');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('46', '과일');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('47', '불고기');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('47', '해산물');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('47', '샐러드');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('48', '해물파전');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('48', '해산물');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('48', '피자');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('49', '족발');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('49', '초콜릿');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('49', '연어');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('50', '해물파전');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('50', '과일');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('50', '훈제오리');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('51', '해물파전');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('51', '치킨');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('51', '소고기 타르타르');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('52', '잡채');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('52', '피자');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('52', '해산물');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('53', '잡채');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('53', '피자');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('53', '바베큐');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('54', '해물파전');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('54', '피자');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('54', '샐러드');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('55', '잡채');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('55', '초콜릿');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('55', '굴');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('56', '잡채');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('56', '스테이크');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('56', '버섯 요리');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('57', '해물파전');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('57', '파스타');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('57', '피자');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('58', '갈비찜');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('58', '토마토 요리');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('58', '스테이크');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('59', '잡채');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('59', '양갈비');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('59', '브루스케타');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('60', '잡채');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('60', '과일');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('60', '굴');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('61', '잡채');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('61', '치킨');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('61', '훈제오리');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('62', '갈비찜');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('62', '파스타');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('62', '바베큐');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('63', '잡채');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('63', '해산물');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('63', '스테이크');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('64', '해물파전');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('64', '과일');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('64', '굴');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('65', '해물파전');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('65', '치킨');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('65', '초콜릿');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('66', '갈비찜');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('66', '파스타');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('66', '굴');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('67', '불고기');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('67', '연어');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('67', '초콜릿');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('68', '족발');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('68', '과일');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('68', '피자');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('69', '불고기');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('69', '연어');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('69', '초콜릿');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('70', '족발');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('70', '훈제오리');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('70', '바베큐');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('71', '해물파전');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('71', '스테이크');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('71', '훈제오리');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('72', '회');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('72', '치즈');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('72', '샐러드');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('73', '잡채');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('73', '양갈비');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('73', '훈제오리');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('74', '회');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('74', '해산물');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('74', '브루스케타');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('75', '해물파전');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('75', '감자튀김');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('75', '햄버거');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('76', '해물파전');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('76', '훈제오리');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('76', '소고기 타르타르');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('77', '회');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('77', '브루스케타');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('77', '과일');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('78', '잡채');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('78', '버섯 요리');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('78', '스테이크');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('79', '해물파전');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('79', '바베큐');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('79', '해산물');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('80', '갈비찜');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('80', '소고기 타르타르');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('80', '굴');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('81', '해물파전');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('81', '소고기 타르타르');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('81', '훈제오리');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('82', '해물파전');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('82', '감자튀김');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('82', '버섯 요리');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('83', '불고기');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('83', '초콜릿');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('83', '브루스케타');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('84', '불고기');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('84', '훈제오리');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('84', '굴');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('85', '불고기');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('85', '피자');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('85', '파스타');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('86', '갈비찜');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('86', '토마토 요리');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('86', '훈제오리');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('87', '잡채');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('87', '소고기 타르타르');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('87', '치즈');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('88', '갈비찜');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('88', '양갈비');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('88', '햄버거');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('89', '해물파전');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('89', '파스타');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('89', '훈제오리');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('90', '회');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('90', '버섯 요리');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('90', '브루스케타');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('91', '회');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('91', '굴');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('91', '감자튀김');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('92', '족발');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('92', '샐러드');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('92', '파스타');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('93', '회');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('93', '스테이크');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('93', '샐러드');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('94', '갈비찜');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('94', '햄버거');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('94', '샐러드');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('95', '갈비찜');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('95', '초콜릿');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('95', '감자튀김');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('96', '회');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('96', '과일');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('96', '훈제오리');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('97', '불고기');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('97', '연어');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('97', '훈제오리');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('98', '족발');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('98', '과일');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('98', '치즈');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('99', '갈비찜');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('99', '피자');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('99', '연어');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('100', '갈비찜');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('100', '굴');
INSERT IGNORE INTO Pairing (wine_id, food) VALUES ('100', '토마토 요리');

INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (22, 19, '바디감이 부족한 느낌이에요.', '2024-11-17', 3.1);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (8, 35, '조금 떫은 맛이 나네요.', '2024-11-30', 2.6);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (28, 8, '산미가 강하지만 깔끔합니다.', '2024-11-22', 1.1);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (7, 7, '음식과 페어링하기 좋아요.', '2024-11-14', 4.3);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (40, 14, '적당히 달콤하고 부드럽습니다.', '2024-11-28', 4.6);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (49, 28, '향이 정말 매력적이에요.', '2024-11-28', 4.1);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (16, 33, '이 와인은 고기와 잘 어울립니다.', '2024-11-26', 4.4);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (26, 31, '향이 정말 매력적이에요.', '2024-11-08', 4.1);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (15, 25, '향이 정말 매력적이에요.', '2024-11-28', 3.8);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (39, 10, '적당히 달콤하고 부드럽습니다.', '2024-11-03', 2.4);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (48, 47, '향이 정말 매력적이에요.', '2024-11-29', 4.1);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (31, 7, '이 와인은 고기와 잘 어울립니다.', '2024-11-02', 4.8);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (6, 15, '음식과 페어링하기 좋아요.', '2024-11-18', 4.6);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (49, 50, '첫맛은 좋지만 끝맛이 조금 약해요.', '2024-12-05', 4.0);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (50, 46, '이 와인은 고기와 잘 어울립니다.', '2024-11-07', 2.5);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (22, 13, '음식과 페어링하기 좋아요.', '2024-11-20', 3.8);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (29, 46, '이 와인은 고기와 잘 어울립니다.', '2024-12-07', 2.1);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (14, 15, '조금 떫은 맛이 나네요.', '2024-11-14', 1.5);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (4, 6, '적당히 달콤하고 부드럽습니다.', '2024-11-17', 3.7);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (35, 37, '와인 초보자도 쉽게 마실 수 있을 것 같아요.', '2024-11-12', 3.4);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (35, 44, '산미가 강하지만 깔끔합니다.', '2024-11-27', 4.8);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (25, 15, '조금 떫은 맛이 나네요.', '2024-11-13', 4.3);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (26, 30, '이 와인은 고기와 잘 어울립니다.', '2024-11-28', 2.1);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (9, 24, '조금 떫은 맛이 나네요.', '2024-11-08', 4.8);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (18, 4, '풍미가 정말 좋아요.', '2024-11-06', 4.7);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (8, 38, '음식과 페어링하기 좋아요.', '2024-11-11', 4.8);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (34, 49, '산미가 강하지만 깔끔합니다.', '2024-11-29', 2.1);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (23, 5, '첫맛은 좋지만 끝맛이 조금 약해요.', '2024-11-12', 4.2);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (13, 7, '향이 정말 매력적이에요.', '2024-11-05', 2.9);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (48, 27, '이 와인은 고기와 잘 어울립니다.', '2024-11-15', 4.4);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (31, 29, '음식과 페어링하기 좋아요.', '2024-11-17', 2.5);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (26, 43, '조금 떫은 맛이 나네요.', '2024-11-05', 4.4);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (9, 33, '산미가 강하지만 깔끔합니다.', '2024-11-28', 4.5);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (46, 7, '와인 초보자도 쉽게 마실 수 있을 것 같아요.', '2024-12-09', 4.3);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (8, 6, '와인 초보자도 쉽게 마실 수 있을 것 같아요.', '2024-12-06', 4.9);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (5, 25, '이 와인은 고기와 잘 어울립니다.', '2024-11-06', 3.5);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (37, 24, '바디감이 부족한 느낌이에요.', '2024-11-02', 3.5);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (27, 27, '이 와인은 고기와 잘 어울립니다.', '2024-11-15', 2.7);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (10, 14, '바디감이 부족한 느낌이에요.', '2024-12-06', 4.0);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (29, 16, '음식과 페어링하기 좋아요.', '2024-11-15', 3.1);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (21, 41, '산미가 강하지만 깔끔합니다.', '2024-11-25', 4.8);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (5, 50, '산미가 강하지만 깔끔합니다.', '2024-11-15', 1.4);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (10, 22, '적당히 달콤하고 부드럽습니다.', '2024-11-18', 1.8);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (47, 5, '조금 떫은 맛이 나네요.', '2024-11-12', 4.3);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (28, 40, '첫맛은 좋지만 끝맛이 조금 약해요.', '2024-11-02', 2.8);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (13, 31, '산미가 강하지만 깔끔합니다.', '2024-11-03', 4.4);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (7, 19, '산미가 강하지만 깔끔합니다.', '2024-11-21', 3.0);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (1, 31, '와인 초보자도 쉽게 마실 수 있을 것 같아요.', '2024-12-03', 4.1);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (19, 12, '적당히 달콤하고 부드럽습니다.', '2024-11-23', 4.0);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (41, 44, '적당히 달콤하고 부드럽습니다.', '2024-11-07', 1.8);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (48, 38, '첫맛은 좋지만 끝맛이 조금 약해요.', '2024-11-12', 3.0);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (8, 22, '와인 초보자도 쉽게 마실 수 있을 것 같아요.', '2024-11-09', 3.3);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (39, 27, '산미가 강하지만 깔끔합니다.', '2024-11-09', 1.8);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (23, 50, '음식과 페어링하기 좋아요.', '2024-11-22', 4.2);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (8, 41, '풍미가 정말 좋아요.', '2024-11-08', 2.1);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (31, 15, '적당히 달콤하고 부드럽습니다.', '2024-11-11', 4.2);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (8, 38, '와인 초보자도 쉽게 마실 수 있을 것 같아요.', '2024-11-15', 2.7);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (3, 45, '음식과 페어링하기 좋아요.', '2024-12-09', 1.1);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (34, 9, '바디감이 부족한 느낌이에요.', '2024-11-10', 3.9);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (36, 30, '음식과 페어링하기 좋아요.', '2024-11-10', 4.5);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (33, 12, '풍미가 정말 좋아요.', '2024-11-05', 3.5);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (16, 5, '첫맛은 좋지만 끝맛이 조금 약해요.', '2024-11-28', 4.6);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (29, 9, '음식과 페어링하기 좋아요.', '2024-11-04', 4.2);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (18, 17, '이 와인은 고기와 잘 어울립니다.', '2024-11-27', 4.1);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (1, 46, '적당히 달콤하고 부드럽습니다.', '2024-12-03', 4.7);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (40, 27, '이 와인은 고기와 잘 어울립니다.', '2024-11-25', 4.7);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (34, 15, '와인 초보자도 쉽게 마실 수 있을 것 같아요.', '2024-11-13', 4.3);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (47, 38, '적당히 달콤하고 부드럽습니다.', '2024-12-09', 4.2);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (1, 4, '풍미가 정말 좋아요.', '2024-12-07', 3.7);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (24, 14, '이 와인은 고기와 잘 어울립니다.', '2024-11-11', 1.3);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (43, 48, '첫맛은 좋지만 끝맛이 조금 약해요.', '2024-11-08', 4.0);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (12, 14, '조금 떫은 맛이 나네요.', '2024-11-20', 1.2);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (43, 8, '음식과 페어링하기 좋아요.', '2024-11-08', 4.5);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (13, 41, '산미가 강하지만 깔끔합니다.', '2024-11-28', 4.1);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (15, 50, '음식과 페어링하기 좋아요.', '2024-11-30', 4.0);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (37, 18, '향이 정말 매력적이에요.', '2024-11-04', 4.5);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (8, 1, '향이 정말 매력적이에요.', '2024-12-09', 4.9);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (45, 26, '이 와인은 고기와 잘 어울립니다.', '2024-11-07', 4.7);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (38, 10, '조금 떫은 맛이 나네요.', '2024-11-13', 4.4);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (25, 47, '산미가 강하지만 깔끔합니다.', '2024-12-03', 1.8);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (8, 14, '향이 정말 매력적이에요.', '2024-11-05', 1.5);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (18, 4, '산미가 강하지만 깔끔합니다.', '2024-11-27', 1.8);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (45, 4, '조금 떫은 맛이 나네요.', '2024-11-10', 1.6);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (25, 40, '조금 떫은 맛이 나네요.', '2024-11-06', 4.8);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (19, 33, '풍미가 정말 좋아요.', '2024-11-14', 2.8);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (13, 29, '이 와인은 고기와 잘 어울립니다.', '2024-11-26', 1.5);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (33, 2, '산미가 강하지만 깔끔합니다.', '2024-11-17', 4.7);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (7, 6, '조금 떫은 맛이 나네요.', '2024-11-12', 3.0);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (15, 48, '이 와인은 고기와 잘 어울립니다.', '2024-11-24', 1.5);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (43, 5, '이 와인은 고기와 잘 어울립니다.', '2024-11-02', 4.1);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (36, 46, '풍미가 정말 좋아요.', '2024-12-05', 1.6);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (21, 25, '조금 떫은 맛이 나네요.', '2024-11-24', 4.2);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (45, 17, '바디감이 부족한 느낌이에요.', '2024-12-09', 1.8);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (21, 18, '적당히 달콤하고 부드럽습니다.', '2024-11-06', 1.7);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (25, 36, '바디감이 부족한 느낌이에요.', '2024-11-27', 4.2);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (11, 42, '적당히 달콤하고 부드럽습니다.', '2024-11-03', 3.3);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (34, 9, '첫맛은 좋지만 끝맛이 조금 약해요.', '2024-11-25', 4.9);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (8, 38, '음식과 페어링하기 좋아요.', '2024-12-04', 4.3);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (6, 38, '첫맛은 좋지만 끝맛이 조금 약해요.', '2024-12-09', 4.5);
INSERT IGNORE INTO review (user_id, wine_id, comment, date, rating) VALUES (5, 25, '와인 초보자도 쉽게 마실 수 있을 것 같아요.', '2024-11-28', 2.5);